### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pawelprazak**
I've added a simplest tl;dr getting started information.

### CODE REVIEW

**Comment by pawelprazak** [comment]
I was not able to get the LSP/metals to start thou, I'm probably missing a config or other necessary step.

But got the icon to appear in the IDE and a stack trace in logs:
```
2024-04-10 10:41:08,490 [  29154]   WARN - #c.i.p.l.i.LspServerImpl - MetalsLspServerDescriptor@besom(Initializing;0): Failed to start LSP server
java.lang.RuntimeException: LSP server failed to initialize
	at com.intellij.platform.lsp.impl.connector.Lsp4jServerConnector.E(Lsp4jServerConnector.kt:107)
	at com.intellij.platform.lsp.impl.connector.Lsp4jServerConnector.connect$intellij_platform_lsp_impl(Lsp4jServerConnector.kt:79)
	at com.intellij.platform.lsp.impl.LspServerImpl.I(LspServerImpl.kt:299)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at com.intellij.platform.lsp.impl.connector.Lsp4jServerConnector.E(Lsp4jServerConnector.kt:65)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.platform.lsp.impl.connector.Lsp4jServerConnector.I(Lsp4jServerConnector.kt:61)
	... 12 more
```

**Comment by hmemcpy** [comment]
Thank you! I'm not really sure why it's not loading, but the LSP implementation in IntelliJ is entirely internal and there's no source code available for it. Is your `metals` binary a symlink or the actual file?

**Comment by pawelprazak** [comment]
I've used the homebrew symlink, I'll retry with the actual file.

**Comment by angelozerr** [comment]
If you want to have a free lsp support for IJ  please try https://github.com/redhat-developer/lsp4ij

**Comment by angelozerr** [comment]
If you want to have a free lsp support for IJ  please try https://github.com/redhat-developer/lsp4ij.

If you want to evaluate LSP4IJ with metal without developping an IJ plugin please read https://github.com/redhat-developer/lsp4ij/blob/main/docs%2Fuser-defined-ls%2Fmetals.md

If you like the lsp support and you want to integrate metal in an IJ plugin please read https://github.com/redhat-developer/lsp4ij/blob/main/docs%2FDeveloperGuide.md

**Pull request closed without merging**
